name:       fuzzy-text
version:    "0.1"
author:     Luna Team <contact@luna-lang.org>
maintainer: Luna Team <contact@luna-lang.org>

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall -O2 -threaded
    dependencies:
      - base
      - containers
      - fuzzy-text
      - hspec
      - layered-state
      - lens
      - prologue
      - text

benchmarks:
    searcher-benchmark:
        source-dirs: benchmark
        main: Main.hs
        ghc-options: -Wall -O2 -threaded
        dependencies:
            - base
            - criterion
            - fuzzy-text
    

library:
  source-dirs: src
  ghc-options: -Wall -O2
  dependencies:
    - base
    - containers
    - layered-state
    - lens
    - nested-containers
    - prologue
    - text

default-extensions:
    - AllowAmbiguousTypes
    - ApplicativeDo
    - Arrows
    - BangPatterns
    - BinaryLiterals
    - ConstraintKinds
    - DataKinds
    - DefaultSignatures
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - DoAndIfThenElse
    - DuplicateRecordFields
    - EmptyDataDecls
    - FlexibleContexts
    - FlexibleInstances
    - FunctionalDependencies
    - GeneralizedNewtypeDeriving
    - InstanceSigs
    - LambdaCase
    - LiberalTypeSynonyms
    - MonadComprehensions
    - MultiWayIf
    - MultiParamTypeClasses
    - NamedWildCards
    - NegativeLiterals
    - NoImplicitPrelude
    - NumDecimals
    - OverloadedLabels
    - OverloadedStrings
    - PackageImports
    - QuasiQuotes
    - RankNTypes
    - RecursiveDo
    - RelaxedPolyRec
    - ScopedTypeVariables
    - StandaloneDeriving
    - TemplateHaskell
    - TupleSections
    - TypeApplications
    - TypeFamilies
    - TypeSynonymInstances
    - TypeOperators
    - ViewPatterns
