resolver: lts-9.6

extra-deps: [cond-0.4.1.1]

packages:
- . 
- extra-dep: true
  location: {commit: c1c525d71b5e749f24e26f71d2d1a68019cae850, git: 'git@github.com:luna/prologue.git'}
- extra-dep: true
  location: {commit: deef3486b1e6f35565f7a13bb78123e78a862347, git: 'git@github.com:luna/luna-studio.git'}
  subdirs: [libs/luna-studio-common, libs/scope-searcher]


- extra-dep: true
  location: {commit: 61ff909efd466735cd4820f9ab2c564e324b5546, git: 'git@github.com:luna/container.git'}
- extra-dep: true
  location: {commit: b84f6fcc7b466760327b1d0f2e7150d9f78dfdc6, git: 'git@github.com:luna/convert.git'}
- extra-dep: true
  location: {commit: a6afda3b96efe00938aba61ac12a2f5f2134ff3d, git: 'git@github.com:luna/data-construction.git'}
- extra-dep: true
  location: {commit: 8a5773adba33d71a311ba0b4123b744213b0be91, git: 'git@github.com:luna/data-layer.git'}
- extra-dep: true
  location: {commit: 1c6a4fd165e4b15cad114b0a554e0974fd119223, git: 'git@github.com:luna/functor-utils.git'}
- extra-dep: true
  location: {commit: a1606cccc12cb521acbc598e52c481b9054b42a7, git: 'git@github.com:luna/impossible.git'}
- extra-dep: true
  location: {commit: 3ba7d5da78aab023fc74c44fc7445ffab0bc18e0, git: 'git@github.com:luna/lens-utils.git'}
- extra-dep: true
  location: {commit: 107db9368e95e192d70c0dec274ecfe3592101d2, git: 'git@github.com:luna/typelevel.git'}
- extra-dep: true
  location: {commit: e63e373d67cd8dd7c179a618f5d32f6ffb3abdd3, git: 'git@github.com:luna/monoid'}
- extra-dep: true
  location: {commit: b5f02ced2912501d923c07950789fbcf44a6a9ce, git: 'git@github.com:luna/data-prop.git'}
- extra-dep: true
  location: {commit: 9da4c9b2534693cfe82adeb37f12eaadacb41e62, git: 'git@github.com:luna/data-repr.git'}
- extra-dep: true
  location: {commit: 4f5153aed4944317942ff9025c79f7fc3be85181, git: 'git@github.com:luna/data-rtuple.git'}
